# The base URL of the site
base_url = "https://jlucfarias.github.io"

title = "Blog do João Lucas"
description = "Um blog com meus pensamentos e opiniões"

default_language = "pt-BR"

minify_html = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

author = "João Lucas Farias"

[markdown]
highlight_code = true
highlight_theme = "dracula"

external_links_target_blank = true

bottom_footnotes = true

[extra]
dark_color = "#212121"
light_color = "#fafafa"
