name: Deploy to Github Pages

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create production css
        run: |
          npm ci
          npm run prod
      - name: install zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola
      - name: create preview images
        run: |
          npm run generate:preview
      - name: process preview images
        run: |
          npm run build
      - name: deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
